### ISSUE TITLE
[BUG] Console Error

### ISSUE THREAD

**Issue by Ruomi123** [Tommy131/OwOBlogWebFrame#5]
请按照以下格式发布您的Issue。
------

#### 问题描述: 遇见了什么问题？
> --- 您的问题 ---
[2023-02-03][02:42:14][OwOBlogErrorHandler/EMERGENCY] > E_NOTICE happened: Only variables should be passed by reference in C:\Users\XXXXXXXX\Downloads\\owoframe\src\owoframe\console\Console.php at line 73
Stack trace:
#0 C:\Users\XXXXXXXXXX\Downloads\2\owoframe\owo(29): owoframe\console\Console->init()
{main}

#### 这个错误是如何产生的？
> --- 问题产生原因 ---
不知道

#### 您的服务器运行环境
> --- 服务器环境描述(例如下方) ---
系统: Window 10
OwO版本: 开发版(v1.0.3-dev)
web环境: 
    - Nginx 1.18.0
    - PHP 7.4
    - MySQL 5.7
    - ...

**Comment by Tommy131** [comment]
你好，感谢使用OwOFrame。最近在计划重构框架，您可以先使用Release中的PR版本，该版本为早期稳定版。

**Comment by Tommy131** [comment]
最新开发预览稳定版已经发布，欢迎尝试并且给出反馈 :)
